name: aptos

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pytest
  - flake8
  - click
  - jupyter
  - pyyaml
  - pytorch>=1.1.0
  - torchvision
  - cudatoolkit=10.0
  - tensorflow
  - kaggle
  - pillow
  - scikit-learn
  - opencv
  - seaborn
  - pip:
    - tb-nightly  # https://www.endtoend.ai/pytorch-tensorboard
    - future      # until Tensorboard v1.14 released
    - tqdm
    - efficientnet-pytorch
    - git+https://github.com/khornlund/robust_loss_pytorch
    - -e .